version: '3'
services:
  edit-db:
    image: sogis/oereb-db
    environment:
      PG_DATABASE: edit
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
      PG_WRITE_USER: gretl
      PG_WRITE_PASSWORD: gretl
      PG_READ_USER: ogc_server
      PG_READ_PASSWORD: ogc_server
    volumes:
      - /Users/stefan/pgdata/gb2av:/pgdata:delegated
    networks:
      - gb2av
    ports:
      - "54321:5432"
networks:
  gb2av:

    