FROM bellsoft/liberica-openjdk-alpine-musl:17.0.3

ARG UID=1001
RUN adduser -S gb2av -u $UID

ENV HOME=/work
WORKDIR $HOME

COPY build/libs/gb2av-*-exec.jar ./application.jar
RUN chown $UID:0 . && \
    chmod 0775 . && \
    ls -la

USER $UID
EXPOSE 8080
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
CMD java -XX:MaxRAMPercentage=80.0 -jar application.jar
