CREATE TABLE 
    agi_gb2av.CAMEL_MESSAGEPROCESSED 
    ( 
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        processorName VARCHAR(255),
        messageId VARCHAR(255), 
        createdAt TIMESTAMP 
    )
;

CREATE TABLE 
    agi_gb2av.vollzugsmeldung_av_delta 
    ( 
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        mutationsnummer VARCHAR(255),
        nbident VARCHAR(255),
        delta INTEGER,
        t_datasetname VARCHAR(512) UNIQUE,
        gb_status VARCHAR(255),
        gb_bemerkungen VARCHAR(255),
        gb_grundbucheintrag DATE,
        gb_tagebucheintrag DATE,
        gb_tagebuchbeleg VARCHAR(255),
        av_beschreibung VARCHAR(255),
        av_gueltigkeit VARCHAR(255),
        av_gueltigereintrag VARCHAR(255),
        av_firma VARCHAR(255)
    )
;

COMMENT ON SCHEMA
    agi_gb2av
IS
    'Schema für das Verwalten der Vollzugsmeldungen des Grundbuchs. Fragen: andrea.luescher@bd.so.ch, stefan.ziegler@bd.so.ch'
;

GRANT USAGE ON SCHEMA agi_gb2av TO public, gretl;

GRANT SELECT ON ALL TABLES IN SCHEMA agi_gb2av TO public;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA agi_gb2av TO gretl;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA agi_gb2av TO gretl;
