name: CI/CD

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean build buildDockerImage
      - name: ls
        run: ls -la build/libs/
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
      - name: Push docker image
        run: ./gradlew pushDockerImages
        if: ${{ github.ref == 'refs/heads/master' }}  
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      